# language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zakdim/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zakdim/react-test npm test -- --coverage
  
after_success:
  - docker build -t zakdim/multi-client ./client
  - docker build -t zakdim/multi-nginx ./nginx
  - docker build -t zakdim/multi-server ./server
  - docker build -t zakdim/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push zakdim/multi-client
  - docker push zakdim/multi-nginx
  - docker push zakdim/multi-server
  - docker push zakdim/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-362362122849
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"