# language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zakdim/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zakdim/react-test npm test -- --coverage
  
after_success:
  - docker build -t zakdim/multi-client ./client
  - docker build -t zakdim/multi-nginx ./nginx
  - docker build -t zakdim/multi-server ./server
  - docker build -t zakdim/multi-worker ./worker